"""Initial migration

Revision ID: 167e7119f197
Revises: 279c7ef67e94
Create Date: 2024-07-15 12:01:07.390975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167e7119f197'
down_revision: Union[str, None] = '279c7ef67e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
