"""Fill game_type

Revision ID: 90975e4981f2
Revises: 28e9cc8c0691
Create Date: 2024-07-15 14:05:41.551424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = '90975e4981f2'
down_revision: Union[str, None] = '28e9cc8c0691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


game_type_table = table('game_type',
    column('id', Integer),
    column('name', String)
)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(game_type_table,
        [
            {'id': 1, 'name': 'chameleon'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM game_type WHERE id IN (1)')
    # ### end Alembic commands ###
