"""Add unique constraint to player

Revision ID: ab4aa22fc5d0
Revises: 63225a08f252
Create Date: 2024-07-22 09:31:53.411050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4aa22fc5d0'
down_revision: Union[str, None] = '63225a08f252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('player_game_user_uc', ['game_id', 'user_id'])
    
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint('game_code_uc', ['code'])
    
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.create_unique_constraint('round_game_num_uc', ['game_id', 'num'])
    
    with op.batch_alter_table('round_info', schema=None) as batch_op:
        batch_op.create_unique_constraint('round_info_round_id_key_uc', ['round_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_game_user_uc', type_='unique')
    
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('game_code_uc', type_='unique')
    
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_constraint('round_game_num_uc', type_='unique')
    
    with op.batch_alter_table('round_info', schema=None) as batch_op:
        batch_op.drop_constraint('round_info_round_id_key_uc', type_='unique')
    # ### end Alembic commands ###
