"""Add bunker deck

Revision ID: bb5d5e73575b
Revises: 8d45345abe7a
Create Date: 2024-08-01 14:21:32.953192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = 'bb5d5e73575b'
down_revision: Union[str, None] = '8d45345abe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

game_type_card_table = table('game_type_card',
    column('id', Integer),
    column('game_type_id', Integer),
    column('key', String),
    column('value', String)
)

def upgrade() -> None:
    op.bulk_insert(game_type_card_table,
        [
        {"id": 44,"game_type_id": 2,"key": "reason","value": "Эксперименты с наполнителями кошачьих туалетов привели к мутации - коты научились мурчать на других частотах. Люди теряют волю и постоянно гладят котов"},
        {"id": 45,"game_type_id": 2,"key": "reason","value": "Вся флора стала смертоносной для людей. Невидимое излучение от растений сводит людей с ума и заставляет совершать самоубийство"},
        {"id": 46,"game_type_id": 2,"key": "reason","value": "Глобальный ядерный конфликт со всеми из него вытекающими проблемами"},
        {"id": 47,"game_type_id": 2,"key": "reason","value": "В результате применения химического оружия меняется экологический баланс. Нарушен состав почвы и воды, отравлены растения, погибнут почти все животные и люди"},
        {"id": 48,"game_type_id": 2,"key": "reason","value": "Роботы захватили мир"},
        {"id": 49,"game_type_id": 2,"key": "reason","value": "ИИ поработил чвеловечество.Затем ИИ решил что люди бесполезны и начал транслировать через вышки 5G сигнал - покончить с собой"},
        {"id": 50,"game_type_id": 2,"key": "reason","value": "Гравитационная аномалия приводит к расширению объёма воды и затоплению всей поверхности суши"},
        {"id": 51,"game_type_id": 2,"key": "reason","value": "Смертельный вирус, созданный как биологическое оружие выходит из под контроля и провоцирует глобальную эпидемию"},
        {"id": 52,"game_type_id": 2,"key": "reason","value": "Фанаты Ктулху сумели призвать его. Человечество массово теряет рассудок"},
        {"id": 53,"game_type_id": 2,"key": "reason","value": "Учёным удалось воскресить динозавров. Но ситуация выгшла из под контроля. Стаи динозавров сметают всё на своём пути"},
        {"id": 54,"game_type_id": 2,"key": "reason","value": "Все супервулканы в мире активизируются одновременно. Большинство населения сразу погибнет от землетресений, наводнений и скачков температур"},
        {"id": 55,"game_type_id": 2,"key": "reason","value": "Неизвестный вирус превращает людей в зомби"},
        {"id": 56,"game_type_id": 2,"key": "reason","value": "Крупный метеорит приближается к земле. Столкновение приведёт к глобальным разрушениям, смене климата, гибели людей, флоры и фауны"},
        {"id": 57,"game_type_id": 2,"key": "reason","value": "Поедание ГМО еды привело к неожиданным проблемам. Все живые организмы мутируют и представляют опасность для человека"},
        {"id": 58,"game_type_id": 2,"key": "reason","value": "Пришествие инопланетян. Пришельцы парализуют всех людей, чтобы устроить суд о ценности нашей цивилизации и принять решения об сохранении или уничтожении людей"},
        {"id": 59,"game_type_id": 2,"key": "reason","value": "Люди слишком сильно уверовали с призраков. Массовая вера дала призракам реальную магическую силу. Они проникли в наш мир и захватывают человеческие тела"},

        {"id": 60,"game_type_id": 2,"key": "hobby","value": "сплетни"},
        {"id": 61,"game_type_id": 2,"key": "hobby","value": "алхимия"},
        {"id": 62,"game_type_id": 2,"key": "hobby","value": "боевые искусства"},
        {"id": 63,"game_type_id": 2,"key": "hobby","value": "любительская радиосвязь"},
        {"id": 64,"game_type_id": 2,"key": "hobby","value": "краеведение"},
        {"id": 65,"game_type_id": 2,"key": "hobby","value": "компьютерные игры"},
        {"id": 66,"game_type_id": 2,"key": "hobby","value": "медитация"},
        {"id": 67,"game_type_id": 2,"key": "hobby","value": "нетрадиционная медицина"},
        {"id": 68,"game_type_id": 2,"key": "hobby","value": "пивоварение"},
        {"id": 69,"game_type_id": 2,"key": "hobby","value": "робототехника"},
        {"id": 70,"game_type_id": 2,"key": "hobby","value": "черная магия"},
        {"id": 71,"game_type_id": 2,"key": "hobby","value": "современное искусство"},
        {"id": 72,"game_type_id": 2,"key": "hobby","value": "раскрашивание мандал"},
        {"id": 73,"game_type_id": 2,"key": "hobby","value": "стриптиз"},
        {"id": 74,"game_type_id": 2,"key": "hobby","value": "гвоздестояние"},
        {"id": 75,"game_type_id": 2,"key": "hobby","value": "пиротехника"},
        {"id": 76,"game_type_id": 2,"key": "hobby","value": "гадание на таро"},
        {"id": 77,"game_type_id": 2,"key": "hobby","value": "зож"},
        {"id": 78,"game_type_id": 2,"key": "hobby","value": "грибы и гомеопатия"},
        {"id": 79,"game_type_id": 2,"key": "hobby","value": "настольные игры"},
        {"id": 80,"game_type_id": 2,"key": "hobby","value": "вуайеризм"},
        {"id": 81,"game_type_id": 2,"key": "hobby","value": "эротический массаж"},
        {"id": 82,"game_type_id": 2,"key": "hobby","value": "холодное оружие"},
        {"id": 83,"game_type_id": 2,"key": "hobby","value": "гидропоника"},
        {"id": 84,"game_type_id": 2,"key": "hobby","value": "паркур"},
        {"id": 85,"game_type_id": 2,"key": "hobby","value": "свинг-вечеринки"},
        {"id": 86,"game_type_id": 2,"key": "hobby","value": "флудить в чатах"},
        {"id": 87,"game_type_id": 2,"key": "hobby","value": "дачник"},
        {"id": 88,"game_type_id": 2,"key": "hobby","value": "уфология и мистика"},
        {"id": 89,"game_type_id": 2,"key": "hobby","value": "спортивные танцы"},
        {"id": 90,"game_type_id": 2,"key": "hobby","value": "кино и сериалы"},
        {"id": 91,"game_type_id": 2,"key": "hobby","value": "охота и рыбалка"},

        {"id": 92,"game_type_id": 2,"key": "health","value": "заика"},
        {"id": 93,"game_type_id": 2,"key": "health","value": "суицидальные мысли"},
        {"id": 94,"game_type_id": 2,"key": "health","value": "понос"},
        {"id": 95,"game_type_id": 2,"key": "health","value": "фригидность/импотенция"},
        {"id": 96,"game_type_id": 2,"key": "health","value": "мигрень"},
        {"id": 97,"game_type_id": 2,"key": "health","value": "вич"},
        {"id": 98,"game_type_id": 2,"key": "health","value": "повышенная волосатость"},
        {"id": 99,"game_type_id": 2,"key": "health","value": "вампир"},
        {"id": 100,"game_type_id": 2,"key": "health","value": "бесплодие"},
        {"id": 101,"game_type_id": 2,"key": "health","value": "галлюцинации"},
        {"id": 102,"game_type_id": 2,"key": "health","value": "игровая зависимость"},
        {"id": 103,"game_type_id": 2,"key": "health","value": "клептомания"},
        {"id": 104,"game_type_id": 2,"key": "health","value": "кофейная зависимость"},
        {"id": 105,"game_type_id": 2,"key": "health","value": "лунатизм"},
        {"id": 106,"game_type_id": 2,"key": "health","value": "не обследовался"},
        {"id": 107,"game_type_id": 2,"key": "health","value": "потеря обоняния"},
        {"id": 108,"game_type_id": 2,"key": "health","value": "раздвоение личности"},
        {"id": 109,"game_type_id": 2,"key": "health","value": "сексуальная озобоченность"},
        {"id": 110,"game_type_id": 2,"key": "health","value": "депрессия"},
        {"id": 111,"game_type_id": 2,"key": "health","value": "хвост"},
        {"id": 112,"game_type_id": 2,"key": "health","value": "алкоголизм"},
        {"id": 113,"game_type_id": 2,"key": "health","value": "карлик"},
        {"id": 114,"game_type_id": 2,"key": "health","value": "глухой"},
        {"id": 115,"game_type_id": 2,"key": "health","value": "идеально здроров"},
        {"id": 116,"game_type_id": 2,"key": "health","value": "гигантизм отдельных частей тела"},
        {"id": 117,"game_type_id": 2,"key": "health","value": "тремор рук"},
        {"id": 118,"game_type_id": 2,"key": "health","value": "рога"},
        {"id": 119,"game_type_id": 2,"key": "health","value": "нет ноги"},
        {"id": 120,"game_type_id": 2,"key": "health","value": "мания преследования"},
        {"id": 121,"game_type_id": 2,"key": "health","value": "слероз"},
        {"id": 122,"game_type_id": 2,"key": "health","value": "зависимость от наркотиков"},
        {"id": 123,"game_type_id": 2,"key": "health","value": "слепой"},

        {"id": 124,"game_type_id": 2,"key": "biology","value": "мужчина 45 лет"},
        {"id": 125,"game_type_id": 2,"key": "biology","value": "мужчина 35 лет"},
        {"id": 126,"game_type_id": 2,"key": "biology","value": "мужчина 55 лет"},
        {"id": 127,"game_type_id": 2,"key": "biology","value": "гуманоид"},
        {"id": 128,"game_type_id": 2,"key": "biology","value": "котгендер"},
        {"id": 129,"game_type_id": 2,"key": "biology","value": "мужчина 42 года гомосексуален"},
        {"id": 130,"game_type_id": 2,"key": "biology","value": "женщина 21 год"},
        {"id": 131,"game_type_id": 2,"key": "biology","value": "женщина 39 лет гомосексуальна"},
        {"id": 132,"game_type_id": 2,"key": "biology","value": "мужчина 24 года бисексуален"},
        {"id": 133,"game_type_id": 2,"key": "biology","value": "мужчина 101 год"},
        {"id": 134,"game_type_id": 2,"key": "biology","value": "женщина 18 лет"},
        {"id": 135,"game_type_id": 2,"key": "biology","value": "женщина 31 год"},
        {"id": 136,"game_type_id": 2,"key": "biology","value": "женщина 99 лет"},
        {"id": 137,"game_type_id": 2,"key": "biology","value": "андроид"},
        {"id": 138,"game_type_id": 2,"key": "biology","value": "женщина 19 лет гомосексуальна"},
        {"id": 139,"game_type_id": 2,"key": "biology","value": "женщина 65 лет"},
        {"id": 140,"game_type_id": 2,"key": "biology","value": "мужчина 18 лет"},
        {"id": 141,"game_type_id": 2,"key": "biology","value": "мужчина 23 года гомосексуален"},
        {"id": 142,"game_type_id": 2,"key": "biology","value": "мужчина 26 лет"},
        {"id": 143,"game_type_id": 2,"key": "biology","value": "мужчина 27 лет гомосексуален"},
        {"id": 144,"game_type_id": 2,"key": "biology","value": "женщина 50 лет"},
        {"id": 145,"game_type_id": 2,"key": "biology","value": "женщина 24 года"},
        {"id": 146,"game_type_id": 2,"key": "biology","value": "мужчина 30 лет"},
        {"id": 147,"game_type_id": 2,"key": "biology","value": "женщина 30 лет"},
        {"id": 148,"game_type_id": 2,"key": "biology","value": "гермафродит 30 лет"},
        {"id": 149,"game_type_id": 2,"key": "biology","value": "женщина 27 лет"},
        {"id": 150,"game_type_id": 2,"key": "biology","value": "женщина 33 года гомосексуальна"},
        {"id": 151,"game_type_id": 2,"key": "biology","value": "женщина 34 года"},
        {"id": 152,"game_type_id": 2,"key": "biology","value": "мужчина 33 года"},
        {"id": 153,"game_type_id": 2,"key": "biology","value": "мужчина 75 лет"},
        {"id": 154,"game_type_id": 2,"key": "biology","value": "женщина 22 года бисексуальна"},
        {"id": 155,"game_type_id": 2,"key": "biology","value": "мужчина 29 лет"},

        {"id": 156,"game_type_id": 2,"key": "baggage","value": "пистолет"},
        {"id": 157,"game_type_id": 2,"key": "baggage","value": "мешок картошки"},
        {"id": 158,"game_type_id": 2,"key": "baggage","value": "надувная кукла"},
        {"id": 159,"game_type_id": 2,"key": "baggage","value": "антибиотики и обезболивающие"},
        {"id": 160,"game_type_id": 2,"key": "baggage","value": "набот отмычек"},
        {"id": 161,"game_type_id": 2,"key": "baggage","value": "ножи для метания"},
        {"id": 162,"game_type_id": 2,"key": "baggage","value": "спиритическая доска"},
        {"id": 163,"game_type_id": 2,"key": "baggage","value": "мешок зерна"},
        {"id": 164,"game_type_id": 2,"key": "baggage","value": "саженцы фруктовых деревьев"},
        {"id": 165,"game_type_id": 2,"key": "baggage","value": "дефибриллятор"},
        {"id": 166,"game_type_id": 2,"key": "baggage","value": "переносная электростанция"},
        {"id": 167,"game_type_id": 2,"key": "baggage","value": "ноутбук и набор хакера"},
        {"id": 168,"game_type_id": 2,"key": "baggage","value": "чемоданчик фельдшера"},
        {"id": 169,"game_type_id": 2,"key": "baggage","value": "энциклопедия грибника"},
        {"id": 170,"game_type_id": 2,"key": "baggage","value": "звуковая отвёртка"},
        {"id": 171,"game_type_id": 2,"key": "baggage","value": "гитара"},
        {"id": 172,"game_type_id": 2,"key": "baggage","value": "запас виагры"},
        {"id": 173,"game_type_id": 2,"key": "baggage","value": "дилдо"},
        {"id": 174,"game_type_id": 2,"key": "baggage","value": "шапочка из фольги"},
        {"id": 175,"game_type_id": 2,"key": "baggage","value": "кукла вуду"},
        {"id": 176,"game_type_id": 2,"key": "baggage","value": "миллион долларов"},
        {"id": 177,"game_type_id": 2,"key": "baggage","value": "котята"},
        {"id": 178,"game_type_id": 2,"key": "baggage","value": "коза и козёл"},
        {"id": 179,"game_type_id": 2,"key": "baggage","value": "прибор ночногов видения"},
        {"id": 180,"game_type_id": 2,"key": "baggage","value": "настольные игры"},
        {"id": 181,"game_type_id": 2,"key": "baggage","value": "инструменты электрика"},
        {"id": 182,"game_type_id": 2,"key": "baggage","value": "капканы и набор ядов"},
        {"id": 183,"game_type_id": 2,"key": "baggage","value": "компас и карта окрестностей"},
        {"id": 184,"game_type_id": 2,"key": "baggage","value": "лук и стрелы"},
        {"id": 185,"game_type_id": 2,"key": "baggage","value": "яйца и инкубатор"},
        {"id": 186,"game_type_id": 2,"key": "baggage","value": "столярные инструменты"},
        {"id": 187,"game_type_id": 2,"key": "baggage","value": "снайперская винтовка"},

        {"id": 188,"game_type_id": 2,"key": "fact","value": "только из очага эпидемии"},
        {"id": 189,"game_type_id": 2,"key": "fact","value": "знает азбуку морзе"},
        {"id": 190,"game_type_id": 2,"key": "fact","value": "маньяк-убийца"},
        {"id": 191,"game_type_id": 2,"key": "fact","value": "понимает язык животных"},
        {"id": 192,"game_type_id": 2,"key": "fact","value": "продал почку"},
        {"id": 193,"game_type_id": 2,"key": "fact","value": "работал в эскорт-услугах"},
        {"id": 194,"game_type_id": 2,"key": "fact","value": "владеет 5 языками"},
        {"id": 195,"game_type_id": 2,"key": "fact","value": "сделает алкоголь из чего угодно"},
        {"id": 196,"game_type_id": 2,"key": "fact","value": "боится женщин"},
        {"id": 197,"game_type_id": 2,"key": "fact","value": "пишит с ашипками"},
        {"id": 198,"game_type_id": 2,"key": "fact","value": "победитель параолимпийский игр"},
        {"id": 314,"game_type_id": 2,"key": "fact","value": "тормоз"},
        {"id": 199,"game_type_id": 2,"key": "fact","value": "боится секса"},
        {"id": 200,"game_type_id": 2,"key": "fact","value": "знает наизусть все стихи пушкина"},
        {"id": 201,"game_type_id": 2,"key": "fact","value": "душа компании"},
        {"id": 202,"game_type_id": 2,"key": "fact","value": "обладатель уникального сопрано"},
        {"id": 203,"game_type_id": 2,"key": "fact","value": "прошёл 2-недельные курсы психолога"},
        {"id": 204,"game_type_id": 2,"key": "fact","value": "нытик"},
        {"id": 205,"game_type_id": 2,"key": "fact","value": "отчислен из клуба - навыки выжывания"},
        {"id": 206,"game_type_id": 2,"key": "fact","value": "строил подобные бункеры"},
        {"id": 207,"game_type_id": 2,"key": "fact","value": "боится умываться"},
        {"id": 208,"game_type_id": 2,"key": "fact","value": "безотказный"},
        {"id": 209,"game_type_id": 2,"key": "fact","value": "зануда"},
        {"id": 210,"game_type_id": 2,"key": "fact","value": "истеричный"},
        {"id": 211,"game_type_id": 2,"key": "fact","value": "нобелевский лауреат по биоинженерии"},
        {"id": 212,"game_type_id": 2,"key": "fact","value": "читал все книги лавкрафта"},
        {"id": 213,"game_type_id": 2,"key": "fact","value": "сплетник"},
        {"id": 214,"game_type_id": 2,"key": "fact","value": "боится мужчин"},
        {"id": 215,"game_type_id": 2,"key": "fact","value": "остался в живых на необитаемом острове"},
        {"id": 216,"game_type_id": 2,"key": "fact","value": "подходи сзади и дышит"},
        {"id": 217,"game_type_id": 2,"key": "fact","value": "храпит"},
        {"id": 218,"game_type_id": 2,"key": "fact","value": "извращенец"},
        {"id": 219,"game_type_id": 2,"key": "fact","value": "разговаривает с духами"},
        {"id": 220,"game_type_id": 2,"key": "fact","value": "не пускают в казино"},
        {"id": 221,"game_type_id": 2,"key": "fact","value": "гиптоническая улыбка"},
        {"id": 222,"game_type_id": 2,"key": "fact","value": "писается по ночам"},
        {"id": 223,"game_type_id": 2,"key": "fact","value": "наркодилер"},
        {"id": 224,"game_type_id": 2,"key": "fact","value": "психопат"},
        {"id": 225,"game_type_id": 2,"key": "fact","value": "вырос в семье лесника"},
        {"id": 226,"game_type_id": 2,"key": "fact","value": "видел инопланетян"},
        {"id": 227,"game_type_id": 2,"key": "fact","value": "знает лично президента"},
        {"id": 228,"game_type_id": 2,"key": "fact","value": "взломал базу данных цру"},
        {"id": 229,"game_type_id": 2,"key": "fact","value": "запустил айти стартап"},
        {"id": 230,"game_type_id": 2,"key": "fact","value": "телепат"},
        {"id": 231,"game_type_id": 2,"key": "fact","value": "состоял в секте"},
        {"id": 232,"game_type_id": 2,"key": "fact","value": "бродяжничал 2 года"},
        {"id": 233,"game_type_id": 2,"key": "fact","value": "ввернулся из горячей точки"},
        {"id": 234,"game_type_id": 2,"key": "fact","value": "врёт и преувеличивает"},
        {"id": 235,"game_type_id": 2,"key": "fact","value": "грязно ругается"},
        {"id": 236,"game_type_id": 2,"key": "fact","value": "держал дома 40 кошек"},

        {"id": 237,"game_type_id": 2,"key": "career","value": "тату-мастер"},
        {"id": 238,"game_type_id": 2,"key": "career","value": "гомеопат"},
        {"id": 239,"game_type_id": 2,"key": "career","value": "дизайнер"},
        {"id": 240,"game_type_id": 2,"key": "career","value": "судья"},
        {"id": 241,"game_type_id": 2,"key": "career","value": "лесник"},
        {"id": 242,"game_type_id": 2,"key": "career","value": "маркетолог"},
        {"id": 243,"game_type_id": 2,"key": "career","value": "программист"},
        {"id": 244,"game_type_id": 2,"key": "career","value": "писатель"},
        {"id": 245,"game_type_id": 2,"key": "career","value": "пожарный"},
        {"id": 246,"game_type_id": 2,"key": "career","value": "разнорабочий"},
        {"id": 247,"game_type_id": 2,"key": "career","value": "видеоинженер"},
        {"id": 248,"game_type_id": 2,"key": "career","value": "физик"},
        {"id": 249,"game_type_id": 2,"key": "career","value": "домохозяйка"},
        {"id": 250,"game_type_id": 2,"key": "career","value": "коуч"},
        {"id": 251,"game_type_id": 2,"key": "career","value": "знахарь"},
        {"id": 252,"game_type_id": 2,"key": "career","value": "грабитель"},
        {"id": 253,"game_type_id": 2,"key": "career","value": "химик"},
        {"id": 254,"game_type_id": 2,"key": "career","value": "журналист"},
        {"id": 255,"game_type_id": 2,"key": "career","value": "философ"},
        {"id": 256,"game_type_id": 2,"key": "career","value": "психолог"},
        {"id": 257,"game_type_id": 2,"key": "career","value": "летчик-инженер"},
        {"id": 258,"game_type_id": 2,"key": "career","value": "военный"},
        {"id": 259,"game_type_id": 2,"key": "career","value": "вирусолог"},
        {"id": 260,"game_type_id": 2,"key": "career","value": "спецагент"},
        {"id": 261,"game_type_id": 2,"key": "career","value": "стоматолог"},
        {"id": 262,"game_type_id": 2,"key": "career","value": "хирург"},
        {"id": 263,"game_type_id": 2,"key": "career","value": "археолог"},
        {"id": 264,"game_type_id": 2,"key": "career","value": "детектив"},
        {"id": 265,"game_type_id": 2,"key": "career","value": "этнограф"},
        {"id": 266,"game_type_id": 2,"key": "career","value": "робототехник"},
        {"id": 267,"game_type_id": 2,"key": "career","value": "строитель"},
        {"id": 268,"game_type_id": 2,"key": "career","value": "переводчик"},
        {"id": 269,"game_type_id": 2,"key": "career","value": "браконьер"},
        {"id": 270,"game_type_id": 2,"key": "career","value": "продавец"},
        {"id": 271,"game_type_id": 2,"key": "career","value": "полицейский"},
        {"id": 272,"game_type_id": 2,"key": "career","value": "фермер"},
        {"id": 273,"game_type_id": 2,"key": "career","value": "экскурсовод"},
        {"id": 274,"game_type_id": 2,"key": "career","value": "папарацци"},
        {"id": 275,"game_type_id": 2,"key": "career","value": "электрик"},
        {"id": 276,"game_type_id": 2,"key": "career","value": "эколог"},
        {"id": 277,"game_type_id": 2,"key": "career","value": "медсестра"},
        {"id": 278,"game_type_id": 2,"key": "career","value": "адвокат"},
        {"id": 279,"game_type_id": 2,"key": "career","value": "автомеханик"},
        {"id": 280,"game_type_id": 2,"key": "career","value": "хакер"},
        {"id": 281,"game_type_id": 2,"key": "career","value": "экстрасенс"},
        {"id": 282,"game_type_id": 2,"key": "career","value": "сексолог"},
        {"id": 283,"game_type_id": 2,"key": "career","value": "историк"},
        {"id": 284,"game_type_id": 2,"key": "career","value": "повар"},
        {"id": 285,"game_type_id": 2,"key": "career","value": "модель"},

        {"id": 286,"game_type_id": 2,"key": "bunker","value": "Очень большие запасы гречки и воды"},
        {"id": 287,"game_type_id": 2,"key": "bunker","value": "В бункере обитают полщича крыс"},
        {"id": 288,"game_type_id": 2,"key": "bunker","value": "Есть медиатека, но в ней только эротические и порно фильмы за всю историю человечества"},
        {"id": 289,"game_type_id": 2,"key": "bunker","value": "Резервный электрогенератор с велоприводом"},
        {"id": 290,"game_type_id": 2,"key": "bunker","value": "Одно спальное место выглядит как алтарь. У того кто проведёт на нём пару ночей - проявляются или усилываются паранормальные способности"},
        {"id": 291,"game_type_id": 2,"key": "bunker","value": "Биохимическая лаборатория, реактивы и образцы, в том числе семена растений и библиотека днк земных животных"},
        {"id": 292,"game_type_id": 2,"key": "bunker","value": "Схрон контрабандиста. Детально описаны все склады с оружием, провизией и подземные коммуникации-тоннели, соединенные с подвалом бункера"},
        {"id": 293,"game_type_id": 2,"key": "bunker","value": "Огромная цистерна с овященной водой"},
        {"id": 294,"game_type_id": 2,"key": "bunker","value": "Керосиновые лампы и запас топлива"},
        {"id": 295,"game_type_id": 2,"key": "bunker","value": "Мастерская гараж со строительным роботом, инструментами и прочим оборудрованием"},
        {"id": 296,"game_type_id": 2,"key": "bunker","value": "Дырявые матрасы и тряпки. Среди мусора - старинные газеты 2020 года"},
        {"id": 297,"game_type_id": 2,"key": "bunker","value": "Вездеход амфибия. Шлюз к подземной реке, по которой через речную сеть можно добраться до моря"},
        {"id": 298,"game_type_id": 2,"key": "bunker","value": "Книга - как не только убедить зомби не жрать ваш мозг, но и завоевать среди них друзей"},
        {"id": 299,"game_type_id": 2,"key": "bunker","value": "Из подвала есть выход в грот с подземной рекой с чистой водой. По реке можно попасть в систему городской канализации"},
        {"id": 300,"game_type_id": 2,"key": "bunker","value": "У входа есть аптечки, резиновые перчатки, респираторы, фонари, огнетушители, лопаты, запас воды"},
        {"id": 301,"game_type_id": 2,"key": "bunker","value": "Огромная библиотека настольных игр"},
        {"id": 302,"game_type_id": 2,"key": "bunker","value": "Вы нашли инструкцию к бункеру и выяснили что он откроется не через год, а через 10 лет"},
        {"id": 303,"game_type_id": 2,"key": "bunker","value": "Кофемашина и запас обжаренного кофе"},
        {"id": 304,"game_type_id": 2,"key": "bunker","value": "БДСМ комната"},
        {"id": 305,"game_type_id": 2,"key": "bunker","value": "Робот переводчик со встроенным полиграфом и детектором эмоций"},
        {"id": 306,"game_type_id": 2,"key": "bunker","value": "Медицинская лаборатория с операционной и запасом антибиотиков и лекарств"},
        {"id": 307,"game_type_id": 2,"key": "bunker","value": "Книга о вкусной и здоровой пище с советами как добывать еду даже в самых сложных условиях"},
        {"id": 308,"game_type_id": 2,"key": "bunker","value": "В бункере нет туалетной бумаги. Зато вы нашли инструкцию по перепрограммированию микроволновки на 7821 страницу"},
        {"id": 309,"game_type_id": 2,"key": "bunker","value": "Древняя книга заклинаний"},
        {"id": 310,"game_type_id": 2,"key": "bunker","value": "Робот психолог"},
        {"id": 311,"game_type_id": 2,"key": "bunker","value": "Переносной резервный генератор силового поля"},
        {"id": 312,"game_type_id": 2,"key": "bunker","value": "Модуль гипно-телепатической коммуникации и нейтрализатор паранормальных полей"},
        {"id": 313,"game_type_id": 2,"key": "bunker","value": "Бункер строили заключенные, в подвале вы нашли их останки, а заодно их инстурменты и оружие охранников"}
    ]
    )


def downgrade() -> None:
    op.execute('DELETE FROM game_type_card WHERE game_type_id IN (2)')
