"""Add new cards

Revision ID: c004325b0c21
Revises: 0c21025610f1
Create Date: 2024-07-18 17:52:12.397990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = 'c004325b0c21'
down_revision: Union[str, None] = '0c21025610f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

game_type_card_table = table('game_type_card',
    column('id', Integer),
    column('game_type_id', Integer),
    column('key', String),
    column('value', String)
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM game_type_card WHERE id IN (1, 2, 3)')
    op.bulk_insert(game_type_card_table,
        [
        {
            "id": 1,
            "game_type_id": 1,
            "key": "game_card",
            "value": '{"topic": "Жанры в музыке","words": ["Рок", "Хип-хоп", "Кантри", "Джаз", "Техно", "Поп", "Метал", "Блюз", "Классика", "Регги", "Панк", "Фолк", "Электро", "Госпел", "Ска", "Рэп"]}'
        },
        {
            "id": 2,
            "game_type_id": 1,
            "key": "game_card",
            "value": '{"topic": "Природные явления","words": ["Землетрясение", "Вулкан", "Наводнение", "Цунами", "Метель", "Смерч", "Туман", "Гроза", "Дождь", "Снег", "Град", "Молния", "Ураган", "Шторм", "Солнечное затмение", "Полярное сияние"]}'
        }
    ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
