"""Fill game_type_card

Revision ID: c5f9bcc0d74a
Revises: 90975e4981f2
Create Date: 2024-07-15 14:12:41.197963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = 'c5f9bcc0d74a'
down_revision: Union[str, None] = '90975e4981f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

game_type_card_table = table('game_type_card',
    column('id', Integer),
    column('game_type_id', Integer),
    column('key', String),
    column('value', String)
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(game_type_card_table,
        [
            {'id': 1, 'game_type_id': 1, 'key': 'game_card', 
                'value': '{"words":["Солнце","Луна","Океан","Гора","Лес","Река","Пляж","Дерево","Птица","Цветок","Дождь","Облако","Звезда","Песок","Камень","Ветер"]}'},
            {'id': 2, 'game_type_id': 1, 'key': 'game_card', 
                'value': '{"words":["Кошка","Собака","Лев","Тигр","Слон","Обезьяна","Зебра","Кит","Дельфин","Орёл","Волк","Медведь","Лиса","Кролик","Белка","Пингвин"]}'},
            {'id': 3, 'game_type_id': 1, 'key': 'game_card', 
                'value': '{"words":["Яблоко","Банан","Апельсин","Виноград","Клубника","Помидор","Огурец","Морковь","Картофель","Хлеб","Сыр","Молоко","Мясо","Рыба","Яйцо","Орех"]}'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM game_type_card WHERE id IN (1, 2, 3)')
    # ### end Alembic commands ###
