name: Deploy

on:
    workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to deploy'
          required: true
          default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Check files on server
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP '
          echo "Current user: $(whoami)";
          echo "Current directory: $(pwd)";
          ls -la /opt/board2gram;
          ls -la /opt/board2gram/deploy.sh
        '

    - name: Run deploy script on server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no root@128.140.107.170 'bash -s' < /opt/board2gram/deploy.sh